//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchange.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketSquare
    {
        public int mark_id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<int> wal_id { get; set; }
        public Nullable<int> mark_numberOfShares { get; set; }
        public Nullable<bool> mark_aktywny { get; set; }
        public Nullable<decimal> mark_sharePriceBuy { get; set; }
        public Nullable<int> bs_id { get; set; }
        public Nullable<decimal> mark_sharePriceSell { get; set; }
        public Nullable<System.DateTime> mark_dataStart { get; set; }
        public Nullable<System.DateTime> mark_dataEnd { get; set; }
        public Nullable<decimal> mark_TransactionPrice { get; set; }
    
        public virtual BuyingSelling BuyingSelling { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
