//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchange.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.MarketSquare = new HashSet<MarketSquare>();
        }
    
        public int stock_id { get; set; }
        public Nullable<int> stockN_id { get; set; }
        public Nullable<int> stock_maxCount { get; set; }
        public Nullable<int> stock_minCount { get; set; }
        public Nullable<int> stock_count { get; set; }
        public Nullable<bool> stock_aktywny { get; set; }
        public Nullable<decimal> stock_pricie { get; set; }
        public Nullable<System.DateTime> stock_date { get; set; }
        public Nullable<decimal> stock_priceOne { get; set; }
        public string stock_seria { get; set; }
        public Nullable<decimal> stock_priceBuy { get; set; }
        public Nullable<decimal> stock_pricaeSell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketSquare> MarketSquare { get; set; }
        public virtual StockName StockName { get; set; }
    }
}
